name: warehouse_app
description: A Flutter app for warehouse stock management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.8.3
  flutter_svg: ^2.0.7
  provider: ^6.1.5+1
  image_picker: ^1.1.2
  get_it: ^7.6.4
  cupertino_icons: ^1.0.5
  # УДАЛИТЬ эти две строки:
  # intl: ^0.20.2
  # flutter_localizations:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  analyzer: ^6.4.1

flutter:
  # УДАЛИТЬ generate: true
  uses-material-design: true

  assets:
    - ../assets/images/

  # Примечание: дополнительные зависимости и настройки выше